### ISSUE TITLE
Unable to deploy ASP.NET Core 2.0 application to Azure

### ISSUE THREAD

**Issue by craigrbruce** [Azure/app-service-announcements-discussions#10]
I was asked by Azure support to create an issue here as he was unable to determine a problem I am having deploying a .NET Core 2.0 app to Azure.

Support Engineer: Charles Liang
Support Ticket: 117082316224636

I have upgraded my asp.net 1.1 app to 2.0 and now have it running locally. I have a VSTS pipeline which successfully builds and deploys the app to Azure.

Azure does not run the app. Log files are non-existent. The error is `HTTP Error 503.0 - Service Unavailable` Can not start the service.

**Comment by davidebbo** [comment]
Please see https://github.com/Azure/app-service-announcements-discussions/blob/master/.github/ISSUE_TEMPLATE.md.

**Comment by davidebbo** [comment]
See also https://stackoverflow.com/questions/45694286/net-core-2-0-azure-app-service-502-5-error which may be your issue.

**Comment by craigrbruce** [comment]
Thanks, David and apologies for ignoring that template, I was on a support call following instructions.

Anyway, the link to SO ... and solution, fixed the problem for me. Namely: Add 

``` <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" /> ```

to the web project's csproj file

Thanks again.

**Comment by davidebbo** [comment]
No problem, glad that worked!

See also https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/, which does mention adding this line (under Update .NET Core CLI tools section).

**Comment by craigrbruce** [comment]
ugh .. i missed that somehow. As the app was running locally, it slipped under the radar too. 

Cheers
