### ISSUE TITLE
[Discussion] Azure Functions Python Library Breaking Change [Consumption]

### ISSUE THREAD

**Issue by maiqbal11** [Azure/app-service-announcements-discussions#104]
Discussion issue for https://github.com/Azure/app-service-announcements/issues/187.

**Comment by bigdatamoore** [comment]
Hi @maiqbal11 , I am wondering why our function app even had the dependencies on azure-functions and azure-functions-worker in our requiremetnts.txt.  Was that put there by the func init in an older version of the functions core tools, and now it is not?

**Comment by bigdatamoore** [comment]
I did find this discussion on the topic: https://github.com/Azure/azure-functions-core-tools/issues/1194

**Comment by maiqbal11** [comment]
Hi @bigdatamoore, we used to publish these dependencies into the users' `requirements.txt` but moved away from doing that some months ago. The `azure-functions-worker` and `azure-functions` were implementation details for the most part and we didn't want to necessarily expose users to them.

**Comment by andreif-funnel** [comment]
What about `azure-storage-blob`? Is it still needed or can also be removed?

**Comment by maiqbal11** [comment]
@andreif-funnel, you should keep any other `azure` dependencies that you intend to use in your app, including `azure-storage-blob`.
