### ISSUE TITLE
[Discussion] Azure Functions Runtime release 2.0.12590 release

### ISSUE THREAD

**Issue by soninaren** [Azure/app-service-announcements-discussions#105]
Discussion issue for the Azure Functions runtime release 2.0.12590

**Comment by wangpingsx** [comment]
I am using Runtime version: 2.0.12590.0 (~2)

I am using nodejs,

I am trying to integrate Excel Table as my function's output, 

In the integration settings, I am using ClientCredentials for identity.

But i got error in the log:

The graph token is missing an oid. Check your Microsoft Graph binding configuration.

![image](https://user-images.githubusercontent.com/1758819/62125226-7226f280-b2c4-11e9-9152-d5f6ce19bb0b.png)

integration
![image](https://user-images.githubusercontent.com/1758819/62125262-91be1b00-b2c4-11e9-9550-c963cf84845a.png)

**Comment by soninaren** [comment]
@wangpingsx Did this work before in the release version of the function runtime or is this the first time you executing this function?
