### ISSUE TITLE
[Discussion] Azure Functions Python Runtime Breaking Change

### ISSUE THREAD

**Issue by maiqbal11** [Azure/app-service-announcements-discussions#111]
Discussion issue for https://github.com/Azure/app-service-announcements/issues/194.

**Comment by bigdatamoore** [comment]
Hi @maiqbal11, when is this breaking change going to be in effect?

**Comment by maiqbal11** [comment]
Hi @bigdatamoore, this is already in effect. This is meant to be informational for any other users who might encounter issues. This is just a more general version of the previous announcement that was only targeting consumption.

**Comment by bigdatamoore** [comment]
Ok thanks.  So to confirm, is the azure-functions dependency necessary for the python functions? I believe we removed it in our last deployment along with azure-function-worker

**Comment by maiqbal11** [comment]
@bigdatamoore, not strictly necessary in some cases, but the we are looking to provide consistent guidance leading up to general availability that users should include it in their requirements.txt.
