### ISSUE TITLE
[Discussion] Node.js 10.16.3 and Npm 6.9.0

### ISSUE THREAD

**Issue by mhoeger** [Azure/app-service-announcements-discussions#120]
Discussion for deployment of Node.js 10.16.3 and Npm 6.9.0

**Comment by tomkerkhove** [comment]
By when are they being removed or effective-immediately?

**Comment by mhoeger** [comment]
@tomkerkhove - they are being added not removed! :) and those versions are live now!

**Comment by tomkerkhove** [comment]
Woops, my bad 😂
