### ISSUE TITLE
[Discussion] Removal of Azure Functions version 2.0.12808

### ISSUE THREAD

**Issue by yojagad** [Azure/app-service-announcements-discussions#126]
Discussion issue for removal of Azure Functions version 2.0.12808

**Comment by webuniverseio** [comment]
I just learned about removal of older versions from production environment because of announcements. Where can I find more about how this works and what happens with running applications? Thank you.

**Comment by fabiocav** [comment]
@jeffhollan / @dariagrigoriu this is a reasonable documentation ask. @ggailey777 is this something we can track?
