### ISSUE TITLE
Azure Functions 3.0 Go Live

### ISSUE THREAD

**Issue by fabiocav** [Azure/app-service-announcements-discussions#131]
Discussion for the Azure Functions 3.0 Go Live announcement.

**Comment by StefanSchoof** [comment]
Great to read.

Will the [azure-functions-core-tools](https://www.npmjs.com/package/azure-functions-core-tools) version 3 soon be get the latest tag?

**Comment by fabiocav** [comment]
@StefanSchoof that will happen when the defaults are changed in January.

**Comment by b10-dslappendel** [comment]
Is v3 with .NET Core 3.1 available for Linux App Services?
When manually changing the `FUNCTIONS_EXTENSION_VERSION` to `~3`, the runtime version is still at `2.0.12888.0 (~3)` for some reason.

At the same time, a function on a Windows consumption plan successfully swaps to `~3`.

**Comment by cozzu** [comment]
> Is v3 with .NET Core 3.1 available for functions on Linux app service plans?
> When manually changing the `FUNCTIONS_EXTENSION_VERSION` to `~3`, the runtime version is still at `2.0.12888.0 (~3)` for some reason.
> 
> At the same time, a function on a Windows consumption plan successfully swaps to `~3` and returns `3.0.12930.0 (~3)`.

I would also like to know this. Have not seen anything excluding Linux function apps from the 3.0 go live, yet the runtime stays at 2.0 no matter what.

**Comment by fabiocav** [comment]
For Linux apps, the flow still requires a few manual steps (which will not be necessary when the defaults are changed in January):

#### Linux Consumption
-	Update App Setting “FUNCTIONS_EXTENSION_VERSION” to “~3”

#### Linux Dedicated/Premium (2 steps required)
-	Update LinuxFxVersion to point to our v3 images, for example:
    -  Python: the LinuxFxVersion would be – “mcr.microsoft.com/azure-functions/python:2.0-python3.6-appservice”. Change it to “mcr.microsoft.com/azure-functions/python:3.0-python3.6-appservice”. This can be done via “https://resources.azure.com” or using Azure CLI.
-	Update App Setting “FUNCTIONS_EXTENSION_VERSION” to “~3”

**Comment by b10-dslappendel** [comment]
That's literally what I did for our app service plan. `FUNCTIONS_EXTENSION_VERSION` is set to `~3` as I mentioned above. Are there any additional steps for .NET functions in particular?

**Comment by cozzu** [comment]
Thanks, updating the container helped for us.

**Comment by DrBarnabus** [comment]
@fabiocav I just tried that with mcr.microsoft.com/azure-functions/dotnet:3.0-appservice and after doing an Azure Pipelines deployment to our Linux Premium v2 it immediately reset back to 2.0.12888.0 (~3) and the image changed back to microsoft/azure-functions-dotnet-core2.0:2.0.

Is it the Azure Pipelines deployment that is messing it up and if it is, is there any way around it for the time being?

The application works fine as soon as I manually specific the first image mentioned above via either the App Service Container UI or resources.azure.com

I originally mentioned this in https://github.com/Azure/azure-functions-host/issues/5368 but still haven't had any help there after nearly a week.

**Comment by andrew-vdb** [comment]
@fabiocav The guide from @jeffhollan told us not to update host.json, so i have dot net core 3.1 with runtime version 2.0

![image](https://user-images.githubusercontent.com/12871379/71091025-9cf6e200-21a4-11ea-8f41-79eae1b72475.png)

Is this expected? wait until host.json version 3 to use runtime version 3?

**Comment by fabiocav** [comment]
@DrBarnabus it is possible something with Azure Pipelines flow is resetting the version. @ankitkumarr do you have more information on this flow?

@andrew-vdb the version in `host.json` doesn't influence the runtime version. That is purely the version of that file. For existing apps, you can also change the `FUNCTIONS_EXTENSION_VERSION` app setting to `~3`, which should have the same effect.

**Comment by atulloh** [comment]
I can see that the .NET Core 3.1 runtime is installed on the Windows consumption plan service. Will the 3.1 SDK eventually be installed also? (This will allow us to deploy our v3 functions app through the portal's built in CI (I think). See issue: https://github.com/Azure/Azure-Functions/issues/1435

**Comment by atulloh** [comment]
> ... Will the 3.1 SDK eventually be installed also? 

Ignore my previous comment, I see that this is already in the works: https://github.com/Azure/app-service-announcements/issues/217

**Comment by ankitkumarr** [comment]
@DrBarnabus, after updating the `linuxFxVersion` and  `FUNCTIONS_EXTENSION_VERSION`, were you able to verify that the function app moved to v3? That's odd if the deployment task is updating your `linuxFxVersion` (for non custom containers). What is the name of the Azure pipelines task you are using? I can take a look at it.

> Would it work correctly if I packaged my Functions App into a docker image that extended mcr.microsoft.com/azure-functions/dotnet:3.0-appservice and used that manually?

Yes, that should work as well. Please be sure to use a public image or setup the credentials if using a private image from a registry. Here's our [official documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image). You can use the 3.0 image as the base image for your custom image, as you mentioned.

**Comment by Rambalac** [comment]
@ankitkumarr `FUNCTIONS_EXTENSION_VERSION` is set to ~3
What is `linuxFxVersion` and how it can be set in run-from-zip deployment?
If you mean Configuration - General settings - Stack settings that's App service setting only, Linux Functions never had it.

**Comment by ankitkumarr** [comment]
@Rambalac, I was talking about "Linux App Service" and  "Linux Elastic Premium" plans.
You don't have to update `LinuxFxVersion` for "Linux Consumption" plans (Fabio's comment above).

To update `LinuxFxVersion`, you could use Azure CLI or resource.azure.com as Fabio commented above. But, I just realize it can be done from portal as well.

**Note: this is only for Linux App Service or Linux Elastic Premium**

From the portal function app blade, go to "Platform features" -> "Container settings". 

![image](https://user-images.githubusercontent.com/16520682/71285759-d7828b00-231a-11ea-9046-f63808d648df.png)

You will see a textbox for "Image and optional tag". There you can change the image to v3. For example, `mcr.microsoft.com/azure-functions/python:2.0-python3.7-appservice` -> `mcr.microsoft.com/azure-functions/python:2.0-python3.7-appservice`, and save.

![image](https://user-images.githubusercontent.com/16520682/71285906-22040780-231b-11ea-8d20-adca1044cb2f.png)

You'd also need to update `FUNCTIONS_EXTENSION_VERSION` App Setting to `~3`.

After you do both of these, it may take a few minutes for your app to move to v3.

**Comment by DrBarnabus** [comment]
@ankitkumarr Interestingly, in the UI for the Task on dev.azure.com it shows as this:

![image](https://user-images.githubusercontent.com/16451892/71360121-a5756100-2586-11ea-844d-ba394271cd7a.png)

But if I click View as YAML then it shows the runtimeStack being set to v2.0.

```yaml
steps:
- task: AzureFunctionApp@1
  displayName: 'Azure Function App Deploy'
  inputs:
    azureSubscription: <subscriptionName>
    appType: functionAppLinux
    appName: <appName>
    package: <packageZipLocation>
    runtimeStack: 'DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0'
```

So the Runtime Stack option in the UI, which only shows .NET or Javascript as valid options, when set to .NET must be setting `DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0` as the `LinuxFxVersion`.

I will try to set it to the correct value or remove that runtimeStack parameter and see if that helps. But it seems like an issue with the `AzureFunctionApp@1` task as opposed to App Service?

**Comment by DrBarnabus** [comment]
After Recreating the `AzureFunctionApp@1` task in the Releases UI on Azure Pipelines and leaving Runtime Stack blank I can confirm this is now working fine and not resetting to the wrong image anymore.

So the issue seems to be with the Azure Pipelines task as opposed to App Service, and it is always setting the same image when you choose .NET as the Runtime Stack.

**Comment by Rambalac** [comment]
Actually you can directly put stack image name to Runntime Stack. Or keep it empty to keep current function image.

**Comment by Rambalac** [comment]
Regardless of having image `mcr.microsoft.com/azure-functions/dotnet:3.0-appservice` and `FUNCTIONS_EXTENSION_VERSION=~3`  function deployed into linux function instance is not working and even does not not show list of functions. Same deployment to windows function instance works without issue.
Deployment log
```
2019-12-26T02:29:02.0795980Z ##[section]Starting: Deploy Function
2019-12-26T02:29:02.0908653Z ==============================================================================
2019-12-26T02:29:02.0908774Z Task         : Azure App Service deploy
2019-12-26T02:29:02.0908853Z Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
2019-12-26T02:29:02.0908951Z Version      : 4.160.2
2019-12-26T02:29:02.0909000Z Author       : Microsoft Corporation
2019-12-26T02:29:02.0909090Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment
2019-12-26T02:29:02.0909172Z ==============================================================================
2019-12-26T02:29:02.7630188Z Got service connection details for Azure App Service:'**********-**********-function-uat'
2019-12-26T02:29:03.0405953Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-26T02:29:04.9531878Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-26T02:29:04.9630183Z Updating App Service Application settings. Data: {"WEBSITES_ENABLE_APP_SERVICE_STORAGE":"true"}
2019-12-26T02:29:05.4062039Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-26T02:29:05.4063513Z Updated App Service Application settings and Kudu Application settings.
2019-12-26T02:29:10.1004144Z Package deployment using ZIP Deploy initiated.
2019-12-26T02:29:53.2810531Z Deploy logs can be viewed at https://**********-**********-function-uat.scm.azurewebsites.net/api/deployments/88848ebf34b8490f898e34dc0e91447b/log
2019-12-26T02:29:53.2810855Z Successfully deployed web package to App Service.
2019-12-26T02:29:53.4559795Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-26T02:29:53.7372673Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-26T02:29:53.8831182Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-26T02:29:55.0429931Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-26T02:29:56.9167416Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-26T02:29:56.9169024Z Successfully added release annotation to the Application Insight : **********-**********-function-uat
2019-12-26T02:29:58.8908345Z Successfully updated deployment History at https://**********-**********-function-uat.scm.azurewebsites.net/api/deployments/3821577327396908
2019-12-26T02:29:59.3141834Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-26T02:29:59.3296730Z App Service Application URL: http://**********-**********-function-uat.azurewebsites.net
2019-12-26T02:30:02.1847606Z ##[section]Finishing: Deploy Function
```

**Comment by Rambalac** [comment]
Regardless of setting image to `mcr.microsoft.com/azure-functions/python:3.0-python3.6-appservice` and `FUNCTIONS_EXTENSION_VERSION` to `~3` no functions are displayed after successful deployment.

**Comment by Rambalac** [comment]
Is MS going to fix v3 functions for Linux?

**Comment by ankitkumarr** [comment]
@DrBarnabus, thanks for confirming. Yeah, you are right that on picking the runtime stack, it is resetting the image. If this task is only meant to publish, and not create the actual function app, then we'd need to follow up on that with Azure DevOps for the expected behavior.

@Rambalac, when you say "no .NET Core 3.0 functions are displayed", are your functions written in .NET or Python? I used the Python image as an example.

- If it's .NET, then you'd want to set the image to `mcr.microsoft.com/azure-functions/dotnet:3.0-appservice`, `FUNCTIONS_EXTENSION_VERSION` to `~3` and ensure that `FUNCTIONS_WORKER_RUNTIME` is set to `dotnet` (It should already be).

- If the functions are Python, then you'd want to set the image to `mcr.microsoft.com/azure-functions/python:3.0-python3.6-appservice`, `FUNCTIONS_EXTENSION_VERSION` to `~3` and ensure that `FUNCTIONS_WORKER_RUNTIME` is set to `python` (It should already be).

If you've already done that and still not seeing your functions, would you mind sharing your function app name and we can take a look?

**Comment by Rambalac** [comment]
@ankitkumarr, `mcr.microsoft.com/azure-functions/dotnet:3.0-appservice` does not change anything. `~3` and `dotnet` were set before.

**Comment by ankitkumarr** [comment]
@Rambalac, would you mind sharing your function app name? I can take a look at what's going on there.

I am unable to reproduce your issue.
I created v3 dotnet functions locally, upgraded my v2 Azure Linux App Service Function app to v3 and then published to that. It worked fine, I can see and execute my v3 functions, as expected.

**Comment by Rambalac** [comment]
@ankitkumarr https://linux-function-test.azurewebsites.net/

**Comment by brandonh-msft** [comment]
@fabiocav  seems we've been missing tagging these announcement issues appropriately. The last few functions ones aren't showing up [here](https://github.com/Azure/app-service-announcements/labels/azure-functions) or [here](https://github.com/Azure/app-service-announcements/issues?q=label%3Aazure-functions+is%3Aclosed)

**Comment by ctolkien** [comment]
> that will happen when the defaults are changed in January.

Jan 30 here - this still planning on going out this month?

**Comment by Rambalac** [comment]
@ankitkumarr So, any news on making Function v3 with core 3.1 working in Linux App Service Plan?

**Comment by mwasplund** [comment]
In case this works for anyone else I was able to resolve this issue by overriding the linuxFxVersion in the release definition and the issue is gone. (Note, this was just a random guess that seems to work)
"-linuxFxVersion dotnet|3.1"
![image](https://user-images.githubusercontent.com/1121076/77037548-d9d2a080-696e-11ea-99e7-8f1055986a16.png)

**Comment by ankitkumarr** [comment]
@mwasplund, I am glad you were able to resolve this. Actually, setting it to any value that's not `"DOCKER|...` should work for .NET. I would say, you can leave it to `DOTNET` as the `3.1` doesn't mean much to the platform. I am going to add documentation on this setting, and update this thread.

@Rambalac, I apologize that I never got a chance to take a look. I was away for a bit in end of January-February, and missed catching up on this. I understand that it may be a bit late now, but were you able to get it working?

**Comment by GiampaoloGabba** [comment]
omg today i lost HOURS for this... thinking that there was problems with my code & dependencies... then i started to play in the azure portal and found (for pure luck) that the container was automatically switched to v2.0....
This should be fixed in the devops portal... ora at least put some documentation or alert in the devops portal.....
