### ISSUE TITLE
[Discussion] End of life support for Go tooling on Azure App Service (on Windows)

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements-discussions#15]
Discussion thread for https://github.com/Azure/app-service-announcements/issues/45

**Comment by Trane9991** [comment]
@davidebbo 
Hey. I'm using golang on the Azure web services.
I think one of the reasons for low usage is a lack of documentation, people simply don't know that it is possible. I found out about the possibility of Go usage on the Azure App Service from some blogpost and decided to give a try. Also, running golang app not integrated with the Logs Stream (or even if there is a way I couldn't find any docs).

Anyway, it is still possible to deploy a binary!

**Comment by davidebbo** [comment]
@Trane9991 another angle is that golang probably runs better on Linux than Windows. Since App Service now has good Linux support, it may make sense to focus golang support in that direction.

**Comment by Trane9991** [comment]
@davidebbo yeah, this makes sense.
But yesterday I decided to try *Web App for Containers* and realized I can't configure networking there, which I need for my project.

I believe it is the same with Linux App Service, right?
Is networking support somewhere on the roadmap?

**Comment by heat** [comment]
Hi, is there documentation how to use go with web app for containers ? I have a go project and want to use in my azure infra

**Comment by iyerusad** [comment]
Can this be consistent for all languages supported by Azure Web Apps/Kudu? Removing Go build/compile during deploy seems inconsistent.

Personally I find using Web hosts as build hosts is meh, but I understand Kudu enables straight from source->deployed (with the Web host/kudu taking care of compile).

Ran into this today when previous node.js apps could do this, but Go support is gone. I'll spin a build pipeline or just push the exe but this disparity in experience chips away at uniform experience with this PaaS offering (Azure Web Apps). Linux/Docker support is great but there is still and likely will be disparity of feature sets of Azure Service Plan running Windows, Linux, or Docker variants.
