### ISSUE TITLE
[Discussion] Proxies Breaking Change

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/app-service-announcements-discussions#16]
https://github.com/Azure/app-service-announcements/issues/50

**Comment by ackonsult** [comment]
Introducing a breaking change like this without any prior notification makes me wonder if Azure Functions are developed far enough for production use.

**Comment by stuartbright** [comment]
@alexkarcher-msft Do you know the approximate timeline for a fix?

**Comment by alexkarcher-msft** [comment]
@ackonsult Proxies is a preview feature, and was subject to have breaking changes published at any time. We're trying to catch as many issues as we can in testing, and will try to have announcements out earlier in the future.

@stuartbright The fix is a few days out, at a minimum.

**Comment by stuartbright** [comment]
@alexkarcher-msft Thanks for the information. Is it possible to revert to the previous behaviour using application setting FUNCTIONS_EXTENSION_VERSION?

**Comment by alexkarcher-msft** [comment]
@stuartbright Nope. That older version of functions will load the most recent version of Proxies.

**Comment by alexkarcher-msft** [comment]
Updated the main issue with one more bug.

All Proxies return 404 | If the application setting ROUTING_EXTENSION_VERSION is ~0.2 all Proxies will return 404 | Remove ROUTING_EXTENSION_VERSION application setting. This is only affecting select subscriptions while we are deploying a fix
-- | -- | --

**Comment by alexkarcher-msft** [comment]
I updated the main issue with another change. This is expected behavior, but still a behavior change.


Proxies No longer accept "?" in routes | Azure/azure-webjobs-sdk-script#1993Proxies that include hardcoded query strings in the route no longer work. Example "/add?a={var}" | Use request.querystring.var to reference query strings. See more details in the issue
-- | -- | --

**Comment by alexkarcher-msft** [comment]
Quick update: We've released all the fixes we planned for these issues. The only change that remains is that proxies will no longer accept "?" in routes.

Thanks for all the help in identifying these issues!
