### ISSUE TITLE
[Discussion] Azure App Service upgrade to Windows Server 2016

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements-discussions#23]
Discussion thread for https://github.com/Azure/app-service-announcements/issues/63

**Comment by darshanrampatel** [comment]
Looking forward to this update!

Is there any way we can check whether our App Service has been updated? Somewhere in the portal?

**Comment by shibayan** [comment]
Which region will be rolled out first?

**Comment by IvanAlekseev** [comment]
Which version will it be 1709 or previous?

**Comment by davidebbo** [comment]
@darshanrampatel @shibayan @IvanAlekseev I started a FAQ on the announcement page to answer those questions. I'll updated it as more questions come up and more info becomes available.

**Comment by paulirwin** [comment]
Do you have a roadmap estimate (even a quarter would be fine) of when HTTP/2 will be made available?

**Comment by davidebbo** [comment]
@paulirwin I just added item to FAQ.

**Comment by JeremyWeir** [comment]
@davidebbo What do you mean by "App Service Environments" in the "Does it also affect App Service Environments" question?

**Comment by davidebbo** [comment]
@JeremyWeir See [App Service Environment](https://docs.microsoft.com/en-us/azure/app-service/environment/intro) doc for details on what it is.

**Comment by jcbohlin** [comment]
Will we be given notice of when our app service will be upgraded?  We would like to verify there are no issues afterward.

**Comment by davidebbo** [comment]
@jcbohlin no, there is no explicit notification mechanism. Note that the situation is not fundamentally different from the monthly updates that the App Service platform goes through. This one includes a newer OS, but we expect sites to continue running smoothly as they move to the new VM.

**Comment by vvidas** [comment]
I have to say, I'm a bit disconcerted that all this is happening over the holidays.  We are short staffed during this time, as I'm sure many companies are as well.  Why was it decided to do this now, rather than wait until after the holidays?  Also, why only 1 business day's notice?  We are new to Azure and this is troubling.

**Comment by odvoskin** [comment]
Hi @vvidas - Note that for the vast majority of customers, there is much more than 1 day notice. We are deploying to a minimal amount of regions this week and will allow concerned customers to deploy and test in those regions. We would not be deploying this update if we weren't positive that any risk could be mitigated. We don't expect this update to have any different effect than our usual monthly update, which will result in a cold start as we shift resources to new instances. If you are already deployed to multiple instances, the impact will be barely visible as traffic is always routed to the active instances.

**Comment by vvidas** [comment]
So why did we only receive a 1 day notice?  And why over the holiday?
I appreciate the info.  I hope that you are correct and no issues occur.  
We've only been on Azure since April of this year so this is really our first experience with a major update/upgrade.

**Comment by odvoskin** [comment]
@vvidas - There is no good time to update the OS, but since there is no major feature development going on at this time in the year, this was a good time to focus on the update to Server we're operating on in the background. Note this also opens up the option for a few highly requested features, like support for HTTP/2.

**Comment by vvidas** [comment]
I just would think over the holidays would not even be a consideration.  Any other time of the year would be better.

**Comment by vvidas** [comment]
Oh and how can we ensure that we get more than 1 day notice in the future. That makes no sense to me that other customers get more notice than we did.

**Comment by MatthewSteeples** [comment]
@vvidas Are you sure you're reading it right? The maintenance window starts today and runs through until January. Unless you're hosted on the test cluster, your update isn't going to be happening today.

**Comment by odvoskin** [comment]
We are not beginning the rolling updates for all the regions for a few days at least, perhaps a week. We will upgrade one region to begin with which has very few resources. As Matthew mentioned, the updates will last throughout January so we are taking extra precaution in case we discover any issue.

**Comment by vvidas** [comment]
@MatthewSteeples I am reading it right because we have no way of know when the host(s) we are on will be upgraded.  It could be today, tomorrow or in 2 weeks.  We have no idea.  
In a previous comment I was told that other customers are given more notice.  I'd like to know why we were not.  One business day does not seem reasonable to me.  The information is unclear as to what and when.  As I said earlier, this is the first time we are going through this and that's why I have all these questions. I just want to understand what we can expect.  I'd appreciate any information at this point.  Thank you all for your comments.

**Comment by vvidas** [comment]
@odvoskin  Thank you, Oded.

**Comment by odvoskin** [comment]
@vvidas - I'm sorry for any inconvenience here. 
Just to shed the right light here, this should not be any different than the regular monthly update we apply each month to all App Service resources. The main thing that is different here is that we communicated this time due to the change in version. However, we don't believe this will cause any outages. The reason we are taking our time and not deploying in a few days as usual, is to be extra cautious. 
I'm not sure where you saw that we are giving customers advance notice. However, we will announce which regions have been upgraded to allow concerned customers to test there in a production environment.
Please follow up with over email if you have concerns you want to share privately - odvoskin@microsoft.com

**Comment by shibayan** [comment]
Will the .NET Framework 4.7.1 be installed at the same time as updating to Windows Server 2016?
(ref. https://github.com/Azure/app-service-announcements/issues/51)

**Comment by davidebbo** [comment]
@shibayan yes, they come together.

**Comment by shibayan** [comment]
@davidebbo Thank you, David.
I’m waiting for update :)

**Comment by m-chau** [comment]
@odvoskin @davidebbo  Please keep us posted on the regions that have been upgraded. I actually have things that only work on Windows Server 2016 and later, so I can't wait for the update and would like to try stuff on it asap. :)

**Comment by odvoskin** [comment]
@m-chau, please send me an email at odvoskin@microsoft.com

**Comment by odvoskin** [comment]
We have now fully deployed Server 2016 to the West Central US region. If you'd like to deploy there for testing, you are welcome to!

**Comment by snekbaev** [comment]
@odvoskin, +1 to @m-chau comment. Also looking forward North Europe update, will migrate to .NET 4.7.1 :)

**Comment by xt0rted** [comment]
Earlier today I received an email from Google Search Console regarding the TLS config on one of my sites. Is this something that the 2016 update will resolve?

Relevant parts of the email:
>Google has detected that your site is using an outdated TLS ciphersuite (ECDHE-RSA-AES256-SHA). As a result, it is easier for third parties to intercept the connection between your users and your site.
>
>To fix this problem, you will need to update your server’s TLS configuration so that it only supports secure ciphersuites. Google recommends the using the following modern ciphersuites: 
>•  TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (c0,2b) 
>•  TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (c0,2c) 
>•  TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (c0,2f) 
>•  TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (c0,30) 
>•  TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 (cc,a8) 
>•  TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305 (cc,a9)

They then link to here for IIS users https://support.microsoft.com/en-us/help/187498/how-to-disable-pct-1-0--ssl-2-0--ssl-3-0--or-tls-1-0-in-internet-infor

**Comment by shibayan** [comment]
After deploying to West Central US and trying it, HTTP 2 seems to be enabled.

![image](https://user-images.githubusercontent.com/1356444/33866204-95066378-df38-11e7-871b-8911976f7154.png)

**Comment by odvoskin** [comment]
@xt0rted - We are not updating any TLS configuration as part of the 2016 rollout. There are plans however to make changes in TLS base levels in 2018 and most likely we'll have changes in cipher suites as well.

@shibayan - good catch about HTTP/2! We have indeed used West Central US for deployment and testing of HTTP/2 which is why you are finding it there. Having said that, we have not deployed it yet for all regions, that will be coming in the next few months.

**Comment by shaulbehr** [comment]
When is this update scheduled to roll out to Azure China?

**Comment by odvoskin** [comment]
@shaulbehr - We don't have a specific time to commit for each region, China included. We are actively deploying across various regions. You can check if you site's resources have been upgraded by checking the methods provided in the FAQ, under "How can I check if my app has been updated?". 
https://github.com/Azure/app-service-announcements/issues/63

**Comment by shaulbehr** [comment]
@odvoskin OK, in that case is there any other way in the meantime I can deploy my .NET 4.7.1 website to an App Service in China?

**Comment by odvoskin** [comment]
@shaulbehr - This is unrelated to the Server 2016 release, but we should probably have .NET 4.7.1 available in all regions, including China, by the end of January 2018.

**Comment by davidebbo** [comment]
@shaulbehr please use #17 for questions about .NET 4.7.1. But schedule wise, 2016 and 4.7.1 will come together, so anything you see here about the 2016 release also applies to 4.7.1.

**Comment by snekbaev** [comment]
North Europe WebApps show Windows Server 2016 now. So far everything seems to be ok, however, in Azure portal -> any North Europe app service -> Overview tab doesn't show statistics anymore, i.e. 5xx errors, data in/out, requests counts - no data available. Assuming that's a known issue and fix is en route. Thank you!

**Comment by darshanrampatel** [comment]
@snekbaev, my North Europe App Service is on 2016 now but still shows the statistics:

![image](https://user-images.githubusercontent.com/14162899/34205594-e6df6dd2-e57a-11e7-8a28-7adb79c4cf9f.png)

**Comment by snekbaev** [comment]
hm, weird, I got 0's for all 5 graphs:

![send](https://user-images.githubusercontent.com/6025502/34206065-999583f0-e58d-11e7-9bf0-320023aaddce.PNG)

**Comment by odvoskin** [comment]
@snekbaev - we have a small issue around security improvements for metering that affects some regions in Europe. This should be mitigated by the end of the day today. Please check again later and let me know if you still see the issue.

**Comment by snekbaev** [comment]
@odvoskin - all is good :) thanks!

**Comment by odvoskin** [comment]
@snekbaev Great to hear! Thanks for the update. Much appreciated.

**Comment by ctolkien** [comment]
Australia East looks to be updated.

**Comment by davidebbo** [comment]
@ctolkien note that each region has multiple scale units. So just because you see one app having been updated does not imply that the entire region has been updated.

**Comment by sampath42** [comment]
How do we check the Date and Time of OS update to my app service 
I wanted to identify when and at what time does OS updated to the app service which is in West europe region

**Comment by odvoskin** [comment]
@sampath42 - are you asking when you can check on the scheduled upgrade? If so, we don't have that information available since we deploy across scale units across various regions. You can however validate if your site has been upgraded using one of the methods listed in the FAQ: https://github.com/Azure/app-service-announcements/issues/63

**Comment by xt0rted** [comment]
Over the last 24 hours my 3 subscriptions in US East have all been updated to Server 2016 🎉

Does Server 2016/IIS 10 have out of the box support for Brotli or Zopfli?

**Comment by odvoskin** [comment]
@xt0rted - I'm not sure about this as we haven't heard about the aspects of what Brotli and Zopfli do. I think the most logical answer would be that you might have to just try and test and out. If this is not supported, we have no way to add it in.

**Comment by PeterDenHollander** [comment]
I have the same issue as snekbaev our webapp in West Europe is updated to server 2016 but overview tab doesn’t show statistics anymore , all graphs got 0,s
App seems to be running fine, as this is a known issue ( at least for north Europe) i assume a fix is underway? Thank you.

**Comment by PeterDenHollander** [comment]
![image](https://user-images.githubusercontent.com/34797960/34322028-d2557bc8-e81c-11e7-8643-ddae00ae3aed.png)

**Comment by sampath42** [comment]
@odvoskin : My App service is updated to 2016 OS successfully, But I wanted to know the date and time when the update happened to my app service.

**Comment by PeterDenHollander** [comment]
The graphs are back online.

**Comment by odvoskin** [comment]
@PeterDenHollander - Sorry about the issue, our deployment got stuck, so the mitigation which was queued up yesterday was not executed for all regions. As you can see, we fully deployed the fix around midnight PST.

**Comment by odvoskin** [comment]
@sampath42 - Is there a specific reason you would want to know when this took place? This is really the same as every other monthly update for App Service when the updates take place on your resources without any indication. If there is an issue or a business reason, you could open a support ticket and the team could investigate your specific resources to see when they got updated.

**Comment by Priyanshini** [comment]
Hello, I see windows 2016 on my western European app service. Suddenly, I started getting the following error:-, with no apparent changes. 
System.UnauthorizedAccessException while using PushPromiseExtension method (line in bold below.)
  public static IHtmlString StyleSheet(this HtmlHelper htmlHelper, string contentPath)
        {
            UrlHelper urlHelper = new UrlHelper(htmlHelper.ViewContext.RequestContext);

            **htmlHelper.ViewContext.RequestContext.HttpContext.Response.PushPromise(contentPath);**

            TagBuilder linkTagBuilder = new TagBuilder("link");
            linkTagBuilder.Attributes.Add("rel", "stylesheet");
            linkTagBuilder.Attributes.Add("href", urlHelper.Content(contentPath));
            
            return new HtmlString(linkTagBuilder.ToString());
        }

![asas](https://user-images.githubusercontent.com/31129183/34356349-eb0273c2-ea62-11e7-8497-efe41a0aa933.png)

**Comment by davidebbo** [comment]
@Priyanshini does this happen randomly or consistently? And does it persist after site restart? It would be ideal if you could share a repro (e.g. as a minimal GitHub repo that demonstrates the issue).

**Comment by Priyanshini** [comment]
@davidebbo : Yes, it happens consistently, even after restart.
`public static IHtmlString StyleSheet(this HtmlHelper htmlHelper, string contentPath)
{
UrlHelper urlHelper = new UrlHelper(htmlHelper.ViewContext.RequestContext);
        **htmlHelper.ViewContext.RequestContext.HttpContext.Response.PushPromise(contentPath);**

        TagBuilder linkTagBuilder = new TagBuilder("link");
        linkTagBuilder.Attributes.Add("rel", "stylesheet");
        linkTagBuilder.Attributes.Add("href", urlHelper.Content(contentPath));
        
        return new HtmlString(linkTagBuilder.ToString());
    }`

The line highlighted above, gives the following error:-
![asas](https://user-images.githubusercontent.com/31129183/34371535-0ad724b8-eaf4-11e7-92ee-2157b98408d1.png)

**Comment by davidebbo** [comment]
@Priyanshini this looks like the exact same content as your previous post. Probably not what you meant? A repro would really help, per my previous entry.

Let's start a separate issue to discuss this, as this one is more for quick questions about the 2016 in general, and we may need to go back and forth a few times to investigate yours.

**Comment by nphmuller** [comment]
A couple of hours ago our Web Apps got migrated. This went fine for most of them, but one became unresponsive after the migration. It's an (ASP).NET Core 2 application, and normally at least something appears in Log Stream through Application Logging when I do a request. But after the migration nothing happened. Killing the w3wp process, which restarted the app, resolved the issue. But in the meantime we had a bit of downtime.

**Comment by davidebbo** [comment]
@nphmuller I believe what you hit is a random .NET Core startup issue that is not specifically related to Server 2016. This is being looked at separately by the .NET Core team.

**Comment by nphmuller** [comment]
@davidebbo Is there anything public, like a GitHub issue, so I can track the problem? Might also be worth mentioning our other .NET Core apps migrated succesfully (3 if swap slots count).

**Comment by davidebbo** [comment]
@nphmuller there have been some internal threads, but I'm not finding a GitHub issue. https://github.com/aspnet/AspNetCoreModule/ would be the right place for it since that's where the issue comes from.

**Comment by davidebbo** [comment]
@nphmuller I found the relevant issue if you want to track it or comment there: https://github.com/aspnet/AspNetCoreModule/issues/260

**Comment by nphmuller** [comment]
@davidebbo Thanks. Seems really helpful. Will try the workaround soon.

**Comment by gluwer** [comment]
After the change to Windows 2016 we started to see w3wp crashes much much more often than before. We use node so also iisnode. On 2012 there were sometimes strange situations or maybe a crash one a week or two. The the situation is like below:

![image](https://user-images.githubusercontent.com/1084706/34453417-07f95230-ed55-11e7-8b24-350855ee715d.png)

In all 6 different apps there are everyday crashes not related to node.exe, as w3wp is restarted every time. We haven't released anything between 2012->2016 switch, node version is the same as before. Maybe it is iisnode issue, but it is also on version 0.2.26 as before. Maybe https://www.bountysource.com/issues/43888703-sporadic-crashs-heap-failures is now happening more often (each instance has sometimes up to 50% load serving up tu 100req/s), We are going to use https://blogs.msdn.microsoft.com/asiatech/2015/12/28/use-crash-diagnoser-site-extension-to-capture-dump-for-intermittent-exception-issues-or-performance-issues-on-azure-web-app/ after the weekend if we can find anything (eventlog.xml has no info about the crash).

**Comment by davidebbo** [comment]
@gluwer we have not had reports of increased crash frequency in 2016. Can you share one sample App Name and UTC time of a crash?

**Comment by gluwer** [comment]
@davidebbo Sure, the app service name is blive-kniffel, and the utc times of crashes on 2017-12-30: 07:50, 14:15, 14:25, 15:45 (I suppose the times reported on portal are rounded), as for the last crash I see in our logs that node started again at 15:49:52)

**Comment by davidebbo** [comment]
@gluwer thanks, we'll investigate. Interestingly, it looks like there hasn't been a crash in almost 24 hours. Did you by a chance change anything that could explain this?

**Comment by gluwer** [comment]
@davidebbo No, we haven't changed anything in configuration or code, but on January 1st we have done node recycle using touch file (iisnode watched files). By the way the crash reoccurred once yesterday (Around 1/1/2018 8:13:13 PM (UTC), On Instance RD00155D522274). But in the same time on blive-kniffel2 it happened three times yesterday (12:15, 14:35, and 15:20).

**Comment by frli** [comment]
Are new instances introduced when an app service is upgraded to 2016 or are the current ones retained and rebooted with a new OS disk (or something like that)? Trying to pinpoint the time when one of our services got upgraded.

**Comment by samsar777** [comment]
Starting from the day when our site has been updated to Windows 2016, an exception is thrown when trying to reach on-premises REST API via Hybrid Connection:

`System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host`

1. This does not happen every time, ca 50% of executions fail.
2. We use both HttpClient and WebRequest.
3. This has never happened in the past before App Service OS update to Windows 2016.
4. API has not been updated in the meantime, nor the underlying database.
5. Querying API via external tool like Fiddler is always successful.

**Comment by davidebbo** [comment]
@gluwer let's take the investigation to https://github.com/Azure/iisnode/issues/48

**Comment by davidebbo** [comment]
@frli your apps do get moved to new VM instances whenever there is an infrastructure upgrade (which happens at least once a month).

**Comment by frli** [comment]
@davidebbo Thanks for clearing that up. Is there any to see exactly when a specific app service (ncg-cdpweb-prod-catalogapp) was updated to server 2016? We had an outage during that day (the 27th) that started before the upgrade occurred but things appear to have gone from bad to worse after the upgrade. A time stamp would be super helpful for us.

Ps: we solved our issue by profiling the App
Service (post upgrade to 2016) with the Application Insight profiler. It revealed that a massive amount of time was spent in lock contention in relation to log4net. We reduced the log levels and latency returned to normal. Log levels and request volumes were the same pre upgrade (2012). No new code was pushed.

**Comment by aleksbol** [comment]
@samsar777 - I would like to investigate this issue and find out what is the cause. Can I ask you to please send me an email, to _aleksbol [at] microsoft.com_? Thank you! 

I am very sorry for the inconvenience this has caused.

**Comment by davidebbo** [comment]
@frli you can tell the last time it was restarted, e.g, by looking at the timestamp of `D:\local\Config\applicationhost.config` from Kudu console. Though it could have been restarted after it got onto 2016, so it's not absolutely reliable.

**Comment by ichivers** [comment]
Once upgraded will we have access to use AMSI (AntiMalware Scan Interface) https://msdn.microsoft.com/en-us/library/windows/desktop/dn889587(v=vs.85).aspx ?

**Comment by ctolkien** [comment]
Can we also assume that this upgrade includes the patches for [Meltdown ](https://meltdownattack.com/)or will there be subsequent updates required for that?

**Comment by davidebbo** [comment]
@ctolkien absolutely, it is part of the upgrade. As you probably guessed, the fact that we had to do this in the first place with limited advance warning was very much related to getting those patches in.

**Comment by NickLocke** [comment]
I'd like to echo the "why over Christmas" comments, and also question the "it's just like any other update" assertion.  We discovered that there was an issue with POSTing large volumes of data which was fine prior to the upgrade.  We raised a severity A premier support call, to find that Microsoft support was short-staffed over the holidays and that we were repeatedly left waiting for available resources.  One of my apps guys found a temporary fix.  Microsoft have confirmed that we are not the only affected customer, they still do not have a root cause, and have the product teams working on it.  All in all, not a good experience.

**Comment by vvidas** [comment]
NickLocke, I'd like to know what you learn on your issue and if a root cause is uncovered. We have been having some odd intermittent problems but as yet I have not created a support ticket because we have been able to resolve them ourselves, but none of the issues we have had were present before the upgrade.  I was not happy that they actually updated East US during the holidays (not even just around the holidays).  Just bad practice.

**Comment by NickLocke** [comment]
Hi vvidas, I will try to keep you posted.  UK South was done on 26th / 27th December - days when hardly anyone was at work to provide support.

**Comment by vvidas** [comment]
Thanks Nick.  That's mind boggling. :(

**Comment by paulirwin** [comment]
@vvidas @NickLocke Given that @davidebbo has confirmed that this timing was due to Spectre/Meltdown, and that the timing was determined by Intel and Google, I'm curious as to how you think Microsoft could have handled this better. Microsoft was in a lose/lose situation between deploying system updates during the holidays, or having customer data be potentially exposed due to this vulnerability. I know that if I were given the choice, I'd choose the former every time.

**Comment by vvidas** [comment]
That was never communicated.  In addition, I was told by a Microsoft support person that this is common practice for them and that have do this every year.

**Comment by paulirwin** [comment]
@vvidas The reasoning was not communicated because Spectre/Meltdown were not made public until January 3 (it was supposed to be January 9). It was kept private specifically so that cloud providers and OS producers like Microsoft have time to patch everything. If it were made public we all would have been at risk until it was patched.

**Comment by vvidas** [comment]
Nevertheless, then MS should have had the necessary resources in place to support.  It also doesn't explain the comment that I was told that it's common practice.  I appreciate your feedback.

**Comment by davidebbo** [comment]
@paulirwin's is exactly correct here.

As you will understand, we were not at liberty to discuss the vulnerability back in December because it had not been publicly disclosed (and Support could not discuss it either).

While we do perform platform updates monthly, this one was a full OS upgrade, so it was bigger than what we normally do.

This was a very unique situation that affected the entire industry, and called for unusual measures. We apologize for any disruption it caused to some customer Web Apps as a result. We do not expect this to be a common situation.

Closing this thread since the upgrade is now complete (which does not block additional comments).

**Comment by NickLocke** [comment]
So, I will continue to wait for an update in respect of the issue that I was actually trying to get a comment on which is the undocumented/unexpected behaviour change (in IIS) between App Services on 2012 and 2016 which, as I said, we were told had affected multiple customers and is currently with the product teams.  When I hear back on that outstanding premier support call, I will feedback here.

**Comment by NickLocke** [comment]
And @paulirwin on how it could have been handled better - simply by not introducing an undocumented change of behaviour which broke a major app, and then having no support staff available to help in a timely fashion.
