### ISSUE TITLE
[Discussion] [Azure Functions] [V4] Application Insights is now available as an extension (breaking change)

### ISSUE THREAD

**Issue by anthonychu** [Azure/app-service-announcements-discussions#248]
Discussion for https://github.com/Azure/app-service-announcements/issues/346

**Comment by booyaa** [comment]
How long have we got before V4 goes live? Presumably, this will also require us to update the function runtime parameter to ~3?

**Comment by anthonychu** [comment]
@fabiocav @brettsam Can you please help with this?

**Comment by brettsam** [comment]
I suspect you need to bump up to: https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/4.0.0-preview2. There are changes in this version that will not remove App Insights dependencies during the build.

**Comment by gzuber** [comment]
This breaking change has been abandoned and is not included in the Functions V4 release. We're re-evaluating the Application Insights Extension, but for now the default integration/behavior remains unchanged.
