### ISSUE TITLE
[Discussion] ARRAffinity cookie is changing to become 'HttpOnly'

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements-discussions#26]
Discussion thread for https://github.com/Azure/app-service-announcements/issues/12

**Comment by davidebbo** [comment]
@andyjballgit asked:

Just come across this as i was running a pen test tool from pen-testtools.com and it flagged that Secure flag was missing on my Azure Web App. Does this change above affect all Web Apps , existing and new ? 

Cookie Name | Flags missing
-- | --
ARRAffinity | Secure

**Comment by davidebbo** [comment]
@andyjballgit it should be affecting all apps, old and new. i.e. the `ARRAffinity` cookie should always be marked as `HttpOnly`.

Note that your tool seems to refer to the `Secure` flag, which is not directly related. This cookie does not contain anything sensitive, so there is no reason to mark it secure.

**Comment by snekbaev** [comment]
@davidebbo That's probably not the right place to ask, but are there plans to allow "Path" to be configured for that cookie? I remember back in 2016/2017 I stumbled upon weird SignalR behaviour in scale-out scenario when connectivity was lost and a re-connection attempt was being made. I don't remember the details, but fixed it by enabling the affinity cookie for the WebApp. The endpoint was a WebAPI application also exposing SignalR. So when I turned on the affinity cookie it obviously also affected the regular REST calls. This is when I thought that it would have been great if I could configure the WebApp just to send the affinity cookie, say, for /signalr path, but ignore everything else.

Thank you!

**Comment by davidebbo** [comment]
@snekbaev Indeed, sort of a side topic. I have not heard of such request before, so I don't think it's on anyone's radar. The right place to make the suggestion is the feedback site: https://feedback.azure.com/forums/169385-web-sites/

**Comment by andyjballgit** [comment]
ah thx David for quick reply re ARRAffinity Secure flag

**Comment by tradefy** [comment]
@davidebbo i was running a Pen Test on an Azure Function app and the test found that the flag was missing from the ARRAffinity cooky.

The change that you said will also be implemented on the Function Apps ?

Cookie name | Security issue
-- | --
ARRAffinity | Missing flag: secure

PS: The test was made yesterday.

**Comment by davidebbo** [comment]
@tradefy that's strange for two reasons:

- Function apps are not supposed to have ARRAffinity enabled at all
- When enabled, it should always be `HttpOnly`.

If you have a repro, please share a URL to a test function that returns this cookie with HttpOnly.

**Comment by glaidler** [comment]
Hi, re. the SecureOnly flag; without this, anyone using Testing in Production will cause a penetration test to fail, irrespective of the lack of sensitive data in the cookie.  Are there any plans to introduce this?

**Comment by af40717** [comment]
Hi, as @glaidler said, the ARRAffinity cookie not being secured causes the pen-tests failing. 
Any plans for this?

**Comment by c-yan** [comment]
Hi, I also got a medium error in the pen-tests because the ARRAffinity cookie does not have a secure flag.
Any plans for this?

**Comment by alincosmin7** [comment]
Hi, Is there any way that we can append the secure tag for ARRAffinity ? I saw this post on msdn blog ( https://blogs.msdn.microsoft.com/webtopics/2018/05/14/securing-the-arraffinity-cookie/ ) I tried that solution for an ASP.NET Core web app but is not working, the ARRAffinity is still without the secure tag.

**Comment by kentongray** [comment]
I'd also like to chime in the same. I agree that it is not a real "risk" but marking it as secure is good practice since it is using HTTPS and should cause no issues.

**Comment by DzonnyDZ** [comment]
Just came across this, actually across #12. I needed this for a scenario when I was handling OAuth form a 3rd-party which absolutely didn't understand how OAuth should be implemented, so the 3rd-party was making call to our servers as part of authentication. That way of course any affinity was lost and I needed to pass affinity somehow around in OAuthe state. I had problems to figure out where to get `WEBSITE_INSTANCE_ID` from.
Hint for anybody who doesn't know where to read it from: Read `WEBSITE_INSTANCE_ID` from `IConfiguration` (which is available via DI in .NET Core) like `config["WEBSITE_INSTANCE_ID"]`.
