### ISSUE TITLE
[Discussion] Newest .NET Core is being deployed to App Service

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements-discussions#40]
Discussion thread for https://github.com/Azure/app-service-announcements/issues/92

**Comment by dchristensen** [comment]
@davidebbo are the versions in the announcement correct?   https://github.com/dotnet/announcements/issues/62 says the new runtime versions should be

- 1.0.10
- 1.1.7
- 2.0.6

**Comment by davidebbo** [comment]
@dchristensen my bad, good catch! Updated.

**Comment by niemyjski** [comment]
Has this been completed?

**Comment by davidebbo** [comment]
Not yet. ETA is tomorrow is all goes well.

**Comment by fabich** [comment]
so I guess not everything went well? :)

**Comment by davidebbo** [comment]
@fabich are you running into an issue? The deployment completed on Friday, as planned: https://github.com/Azure/app-service-announcements/issues/92

**Comment by fabich** [comment]
@davidebbo ahh no, we didn't update yet.
I didn't see that you closed the other issue, I'm sorry.

**Comment by davidebbo** [comment]
My bad, I should have closed this one as well.

**Comment by lkfr** [comment]
dotnet --version
2.1.4

This is the 2.0.5 runtime.
Command executed on a Linux app service with the .NET Core 2.0 runtime stack

**Comment by davidebbo** [comment]
@lkfr sorry, this issue only tracks Windows App Service (I just updated the title).
