### ISSUE TITLE
[Discussion] New version 2.0.11651-alpha of the Preview runtime 

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements-discussions#41]
Discussion thread for https://github.com/Azure/app-service-announcements/issues/94.

**Comment by GregLevenhagen** [comment]
Did the roll out of this hit North Central US earlier today or yesterday? We are now seeing Durable Functions, as part of the Extensions namespace, broken.

**Comment by nzthiago** [comment]
What are the breaking changes? 

The [announcement](https://github.com/Azure/app-service-announcements/issues/94) points to [release notes](https://github.com/Azure/azure-functions-host/releases/tag/v2.0.11651-alpha) but the release notes only say `This release does introduce breaking changes to extensions. Previous extension versions may not continue to work and will require re-installation`. Would be good to know what to look out for

**Comment by davidebbo** [comment]
@nzthiago see the follow up that @paulbatum posted in the announcement yesterday. It has much more details this.

**Comment by nzthiago** [comment]
I read through it earlier, but it seems more like instructions on how to update everything so that it starts working again. I thought there'd be a list of what errors and problems that will start showing up if we don't follow Paul's instructions...

**Comment by davidebbo** [comment]
@nzthiago yes, that's not explicitly mentioned. I think one possible behavior will be that the host will fail to start. i.e. going to the root of the Function App will just fail with `Function host is not running`.

**Comment by davidebbo** [comment]
Here is a more specific one you will see in Portal if you used a SendGrid extension with the old build and then move to new build:

```
The function runtime is unable to start. Microsoft.Azure.WebJobs.Extensions.SendGrid: Method not found: 'Microsoft.Azure.WebJobs.Host.Config.FluentBindingRule`1<!0> Microsoft.Azure.WebJobs.Host.Config.FluentBindingRule`1.AddValidator(System.Action`2<!0,System.Type>)'.
```

**Comment by nzthiago** [comment]
Is there an updated version of the local dev Azure Functions Core Tools on the way that will match this?

**Comment by mayoatbm** [comment]
All our functions in Azure (v2) are currently broken. The portal shows the runtime version of the functions as (2.0.11651) which matches up to this newly released runtime. Am I understanding that correctly? This newly released runtime that has breaking changes is already deployed to azure?

We've followed all the steps  mentioned in the links and we are in a far worse place than we were (and that wasn't a great place to begin with). We can't run the functions anywhere now (locally  in VS or with the CLI or in azure). We were able to do this before upgrading the sdk to 1.0.12 fro  1.0.7). 

Please see the current error below. It doesn't match any of the many similar errors that have been discussed.  

----------------------------------------------
"[3/29/2018 10:40:52 PM] System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions,
Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception f
rom HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions
, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'"

**Comment by davidebbo** [comment]
@nzthiago the new Core Tools should be out later today.

@mayoatbm yes, the new runtime is now fully deployed. Let's work to figure out your situation. In the meantime, if that is really blocking you, you can set `FUNCTIONS_EXTENSION_VERSION=2.0.11587-alpha` in the App Settings to go back to previous build. But this is only a temporary measure, as the old build will later disappear and you should always be on the latest Preview.

**Comment by mayoatbm** [comment]
@davidebbo  Thank you for the super fast response. 

We are well and truly blocked (this issue is currently delaying system test on a enterprise project). Thank you for the temporary workaround (that will help us get us moving). What can i provide to help you and the team troubleshoot our specific exception? May i contact you or the team directly?

**Comment by davidebbo** [comment]
@mayoatbm the error looks identical as https://github.com/Azure/azure-functions-host/issues/2448, though that was opened a month ago.

Let's take the conversation there. Please [share your App Name](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately) on that issue so we can dig deeper.

**Comment by nzthiago** [comment]
I am seeing that exact same "Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions" exception on my dev machine with a v2 C# compiled class function and `Microsoft.NET.Sdk.Functions` 1.0.11 and `Microsoft.Azure.WebJobs.Extensions.CosmosDB` 3.0.0-beta7, when debugging from Visual Studio which I think defaults to an even older version of the core tools...

Will wait for the updated Core Tools to retest, and I'm also monitoring [this](https://github.com/Azure/Azure-Functions/issues/625)

**Comment by davidebbo** [comment]
Status: new core tools are now available on npm and homebrew. VS still needs to update the extension.

**Comment by nzthiago** [comment]
Confirmed that the new core tools fixes the Microsoft.AspNetCore.Mvc.Abstractions error for my local dev as per below (when starting with `func host start`). Will retest when the VS extension is updated too.

**Comment by dipinbehl** [comment]
I have updated the Microsoft.NET.Sdk.Functions to  1.0.12. The logs in the functions apps also suggest that the runtime is at version 2.0.11651.0 (2.0.11651.0-beta1 Commit hash: 626c20039fb17e1d5c79145d7b7c3579cf62a92a to be more precise), but the function still throws the error 'Method not found: 'Void Microsoft.Azure.WebJobs.Host.Config.FluentBindingRule`1.BindToInput(System.Func`2<!0,!!0>)'.' Any help on this?

**Comment by selvasingh** [comment]
@davidebbo - I am bumping into the same issue - `Result: Cannot locate the method signature with the given input Exception: Cannot locate the method signature with the given input Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
 at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:49)
 at java.util.Optional.orElseThrow(Optional.java:290)
 at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:49)
 at ...`

**Comment by MV10** [comment]
@dipinbehl several similar beta5 binding exceptions posted at https://github.com/Azure/azure-webjobs-sdk/issues/1648

**Comment by davidebbo** [comment]
Let's move the discussion to a set of GitHub issues, otherwise we'll end up trying to solve too many distinct cases all in one thread.

@selvasingh yours is with Java and is likely different, so please open separate issue (and give link here for context).

**Comment by davidebbo** [comment]
It took a little longer than we would have wanted, but the updated Azure Functions and WebJobs Tools VS extension is now up. Please go ahead and upgrade. The new version is 15.0.40405.0.

Thanks for your patience on this.

**Comment by mayoatbm** [comment]
@davidebbo  Thanks a ton for the upgrade and the update. We will check it out.
