### ISSUE TITLE
.net Core 2 Error when publishing using Visual Studio 2017 

### ISSUE THREAD

**Issue by jonasTMoreira** [Azure/app-service-announcements-discussions#42]
Guys, I'm having the same problem as this previous topic but I haven't been able to solve it yet.
Can you help?
Is an initial application using .net Core 2

http://mbcore.azurewebsites.net/

**Comment by reyou** [comment]
I did not want to create a new issue but, if I remove this on local, IIS 10 throws same exception. 
What to do in this case?
