### ISSUE TITLE
[Discussion] F# 4.1 for Azure App Service and Azure Functions

### ISSUE THREAD

**Issue by toburger** [Azure/app-service-announcements-discussions#5]
Azure App Service (and therefore also Azure Functions?) at the moment is using the F# 4.0 compiler.
Are there any plans to update the F# runtime to the newer 4.1 version?

**Comment by davidebbo** [comment]
This repo is only to discuss announcements posted by the team. Would you mind moving this to https://github.com/Azure/azure-functions/? Thanks!
