### ISSUE TITLE
[Discussion] IpSecurityRestriction availability for Azure Functions

### ISSUE THREAD

**Issue by suwatch** [Azure/app-service-announcements-discussions#52]
Please use this to discuss `IpSecurityRestriction availability for Azure Functions` questions.

**Comment by rxharr6** [comment]
It is not an acceptable practice to roll back a feature in production that many users find a critical security feature in order to release a new feature...who made this decision? We have clients who will totally loser trust in the reliability of Azure over this.

**Comment by kamaljoshi911** [comment]
Is it fixed now?

**Comment by btardif** [comment]
Back-end API changes and UX are currently scheduled to go out on the week of July 16th. We'll update this thread as we make progress

**Comment by panchagnula** [comment]
The changes are live
