### ISSUE TITLE
.Net Core 2.1 App failing to start in Azure App Service

### ISSUE THREAD

**Issue by Ro3A** [Azure/app-service-announcements-discussions#53]
When deploying my .Net Core 2.1 RC1 app to app service using VSTS, the service fails to start. 

When publishing from Visual studio it works just fine. I compared staging (VSTS deployment) against my production slot (Publish from Visual Studio) and found differences in the [appName].deps.json file. 

The deps.json file in source contains the "-rc1" suffix, but when published via VSTS it does not. 

Here's a diff screen shot. Visual Studio Published file on the left, VSTS on the right:

![image](https://user-images.githubusercontent.com/19931334/41549321-79d41722-72f3-11e8-804c-545310e621d8.png)

Some additional details:

When publishing from visual studio the site extension in the app service is automatically installed. From what I understand, this is not needed for the final bits, which is what I'm using. That said, I've tried it with and without the extension via VSTS and it doesn't make a difference.

Any ideas?

**Comment by davidebbo** [comment]
This is what you should have seen when trying to open an issue in this rep:

Please do not open an issue in this repo! It is not a general purpose issue tracker for app service.

The purpose of this issue tracker is to discuss announcements posted on https://github.com/Azure/app-service-announcements/. All
issues are created by the repo owners, and then the community uses those pre-created issues for discussions.

To report App Service issues, please use [this forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) or StackOverflow. And for Functions issues, use [this forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureFunctions) or StackOveflow. Thanks!
