### ISSUE TITLE
[Discussion] Deployment of .NET Core 1.0.12, 1.1.9, 2.0.9, 2.1.2 to Azure App Service

### ISSUE THREAD

**Issue by watashiSHUN** [Azure/app-service-announcements-discussions#56]
Discussion issue for https://github.com/Azure/app-service-announcements/issues/121

**Comment by paulirwin** [comment]
There isn't any information in the announcement post about timelines. When is this going to be deployed?

**Comment by MisterCrispyFL** [comment]
I would like to know as well. Even a rough idea like "hopefully within a week barring unforeseen circumstances" would be nice.

**Comment by watashiSHUN** [comment]
Mathew is right, the info is hidden in release note: https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.2.md#azure-appservices

**Comment by watashiSHUN** [comment]
The deployment is now complete.
