### ISSUE TITLE
[Discussion] .NET Core 2.0 on Azure App Service

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements-discussions#6]
Discussion thread for https://github.com/Azure/app-service-announcements/issues/26

**Comment by ctolkien** [comment]
Are the final 2.0 bits released? We've heard NetStandard2.0 has been finalised, nothing about NETCore2?

**Comment by davidebbo** [comment]
Not yet. Please listen for news from the Core team to know when the bits are available.

**Comment by ctolkien** [comment]
And this doesn't override the 2.0-Preview2 installs I take it? They are side by side?

**Comment by tjrobinson** [comment]
@davidebbo I assume this means that .NET Core 2.0 is now final, just not public yet? This announcement is a bit confusing.

**Comment by davidebbo** [comment]
@ctolkien it will indeed be side by side with the preview. Though for the SDK, you'll end up automatically using 2.0.0 unless you have a global.json that says otherwise. See #7 for related discussions.

@tjrobinson sorry about the confusion. This was meant to be a heads up that it was coming soon, but at this point we are waiting for the Core team to declare the bits 100% final. I probably should have waited until they did to post this.

**Comment by kemmis** [comment]
@davidebbo Do you have a guestimate on the timeframe in which this will be available for us to use? Are we talking days, weeks, or months?

**Comment by ctolkien** [comment]
@kemmis  Soon ™️

**Comment by davidebbo** [comment]
Sorry, 'soon' is all I can say here :)

**Comment by darewreck54** [comment]
@davidebbo  can you currently publish a .netcore 2.0 app to azure app service?  .netCore 2.0 got released today officially.  when i tried to publish my .net core 2.0 i get errors with the application.  However, if i change it to .net core 1.1 it works perfectly.  The app with .net core 2.0 works perfectly on my local machine.

**Comment by isaac2004** [comment]
@darewreck54 it isn't ready, based on the fact this issue is still open :)

**Comment by ctolkien** [comment]
You can use Kudu, or the command line section of azure app services to run `dotnet --info` to see the version information that you're running under.

**Comment by davidebbo** [comment]
It's partially deployed. Deployment should complete tomorrow morning (PST), if we don't hit any scary issues before that.

If you're eager to play with it today, try a test app in North Central US.

**Comment by ac9999** [comment]
@darewreck54 having the same issue.  upgraded my azure .net core 1.0 project --> .net core 2.0 today and after publishing the webApp to my existing deployment slot, it gave the ERROR : HTTP Error 502.5 - Process Failure.  It seems to work just fine on my development machine.

@microsoft Visual Studio 2017's web deploy to azure --> file publish options --> remove additional files at destination doesn't always work the it was intended and I find I often have to flush it manually as files are always left over during core version upgrades.  Perhaps this would be better suited to be an option in the web portal which clears ALL files so you can publish from scratch.

**Comment by davidebbo** [comment]
@ac9999 see https://github.com/Azure/app-service-announcements/issues/24 relating to deployment issue.

This issue is more to track the deployment of 2.0 in Azure App Service.

**Comment by sebastianbk** [comment]
I upgraded the version of .NET Core SDK on my Azure Web App using the PowerShell interface and [this deployment script](https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.ps1) to run the newest bits on my website. I issued the following command from PS:

```
.\dotnet-install.ps1 -Channel release/2.0.0
```

After that, I can run `dotnet --info`, which shows me that it is now running the latest version:

```
.NET Command Line Tools (2.0.1-servicing-006926)

Product Information:
 Version:            2.0.1-servicing-006926
 Commit SHA-1 hash:  209d0cac73

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.2.9200
 OS Platform: Windows
 RID:         win8-x86
 Base Path:   D:\local\LocalAppData\Microsoft\dotnet\sdk\2.0.1-servicing-006926\

Microsoft .NET Core Shared Framework Host


  Version  : 2.0.0

  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

Then, when I navigate to `D:\home\site\wwwroot\` where my application is deployed and I run `dotnet MyApp.dll` I get this output:

```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:5000 on the IPv6 loopback interface: 'Error -4090 EADDRNOTAVAIL address not available'.
Hosting environment: Production
Content root path: D:\home\site\wwwroot
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:5000 on the IPv6 loopback interface: 'Error -4090 EADDRNOTAVAIL address not available'.
```

It seems as if it starts up correctly. However, when I navigate to my site (on either port 80 or port 443) I get the `HTTP Error 502.5 - Process Failure` error. When I try on port 5000, the browser just hangs for a minute and then times out.

When I refresh my PowerShell session, it's back to version `2.0.0-preview2-006497`, which I guess is because the path to the new version of the SDK is not being persisted in my PATH. I have tried to add the directory of the new SDK to my PATH but I haven't been able to do so. So I haven't been able to see if redeploying or restarting the site resolves the issue, as it naturally defaults back to the preview version.

What should I do to get this working? And what's the time frame for updating all of the Azure Web App instances out there to the newest version? I am in West Europe.

**Comment by kemmis** [comment]
Working for me via the North Central US region hosting. Thanks for such a fast turn around!

**Comment by sebastianbk** [comment]
@davidebbo, thanks for the support on Twitter. I now see the new SDK on my Web App hosted in West Europe.

I went and deployed my app targeting `netcoreapp2.0` using my release definition in VSTS and it seemed to deploy and start correctly. However, when navigating to [my site](https://staging.sensomind.com/) I first got a 503 (Service Unavailable) error. Then after refreshing the page, I am now constantly getting this message:

```
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```

It seems as if it does hit the application but that it is caught in a loop of redirects (or something like it). The path shown in my browser atleast indicates this:

```
https://staging.sensomind.com/Account/LogIn?ReturnUrl=%2FHome%2FError%3FReturnUrl%3D%252FHome%252FError%253FReturnUrl%253D%25252FHome%25252FError%25253FReturnUrl%25253D%2525252FHome%2525252FError%2525253FReturnUrl%2525253D%252525252FHome%252525252FError%252525253FReturnUrl%252525253D%25252525252FHome%25252525252FError%25252525253FReturnUrl%25252525253D%2525252525252FHome%2525252525252FError%2525252525253FReturnUrl%2525252525253D%252525252525252FHome%252525252525252FError%252525252525253FReturnUrl%252525252525253D%25252525252525252FHome%25252525252525252FError%25252525252525253FReturnUrl%25252525252525253D%2525252525252525252FHome%2525252525252525252FError%2525252525252525253FReturnUrl%2525252525252525253D%252525252525252525252FHome%252525252525252525252FError%252525252525252525253FReturnUrl%252525252525252525253D%25252525252525252525252FHome%25252525252525252525252FError%25252525252525252525253FReturnUrl%25252525252525252525253D%2525252525252525252525252FHome%2525252525252525252525252FError%2525252525252525252525253FReturnUrl%2525252525252525252525253D%252525252525252525252525252FHome%252525252525252525252525252FError%252525252525252525252525253FReturnUrl%252525252525252525252525253D%25252525252525252525252525252FHome%25252525252525252525252525252FError%25252525252525252525252525253FReturnUrl%25252525252525252525252525253D%2525252525252525252525252525252FHome%2525252525252525252525252525252FError%2525252525252525252525252525253FReturnUrl%2525252525252525252525252525253D%252525252525252525252525252525252FHome%252525252525252525252525252525252FError%252525252525252525252525252525253FReturnUrl%252525252525252525252525252525253D%25252525252525252525252525252525252FHome%25252525252525252525252525252525252FError%25252525252525252525252525252525253FReturnUrl%25252525252525252525252525252525253D%2525252525252525252525252525252525252FHome%2525252525252525252525252525252525252FError%2525252525252525252525252525252525253FReturnUrl%2525252525252525252525252525252525253D%252525252525252525252525252525252525252FHome%252525252525252525252525252525252525252FError%252525252525252525252525252525252525253FReturnUrl%252525252525252525252525252525252525253D%25252525252525252525252525252525252525252F
```

I have tried cleaning the whole `wwwroot` directory, redeploying the app and restarting the Web App instance. However, none of it seems to work. I haven't had this issue before so I am unsure of how to resolve it.

If it is of any help here is my `web.config`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <clear />
      </rules>
    </rewrite>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="104857600" />
      </requestFiltering>
    </security>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\Sensomind.Web.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
```

**Comment by jeastburn** [comment]
It looks like 2.0.0 just rolled out to East US 2 region so my 2.0.0 app is now working instead of the 502.5 error! Thanks!

**Comment by davidebbo** [comment]
Indeed, the roll out is now complete!

**Comment by ac9999** [comment]
.NET Core 2.0 works for the Canadian East servers.  Thanks.

**Comment by CharlBest** [comment]
I'm still getting this issue in North Europe. Restarted my App Service and republished from Visual Studio but no luck.

**Comment by davidebbo** [comment]
@CharlBest what issue are you referring to? This is a general discussion thread for the deployment of Core 2.0 to App Service, and does not track one issue in particular.

**Comment by CharlBest** [comment]
Oops sorry @davidebbo I should've posted this on the https://github.com/aspnet/IISIntegration/issues/252 My bad. So you want me to raise it there?

**Comment by davidebbo** [comment]
@CharlBest no problem. That does look like the right thread to use. Though it's old and closed, so conceivable opening a new one there with fresh Core 2.0 info will give it better attention (linked to old one).

**Comment by CharlBest** [comment]
Alright @davidebbo will do so. Thanks

**Comment by jgauffin** [comment]
I've migrated from 1.1 to 2.0. I get the following error when deploying to azure:

> Failed to initialize CoreCLR, HRESULT: 0x80004005

What I've tried: https://stackoverflow.com/questions/45962785/migrated-from-asp-net-core-1-1-to-2-0-fails-with-failed-to-initialize-coreclr

**Comment by Fehrox** [comment]
@sebastianbk this exactly describes what I'm currently trying to solve. Did you ever find a solution?

**Comment by kangji536def** [comment]
im so soory to interupt to post here
https://pauio.com/super/ - 슈퍼카지노
