### ISSUE TITLE
[Discussion] Azure Functions Runtime 2.0.11961-alpha release

### ISSUE THREAD

**Issue by mhoeger** [Azure/app-service-announcements-discussions#63]
Discussion issue for the Azure Functions runtime release 2.0.11961-alpha

**Comment by jeffhollan** [comment]
Per question on GA - we are in the final stretch of major changes. No dates to commit to currently @lmemmott but not too much longer.  If you have a scenario and are looking to go into production before we hit GA feel free to send me details and happy to review and see if we can help.  My email is on my profile

**Comment by lmemmott** [comment]
@jeffhollan Sounds good.  Thanks for the update.  We'll watch announcements when it goes GA.
