### ISSUE TITLE
context.bindingData returns an empty object now for optional parameters  !!!

### ISSUE THREAD

**Issue by antoniopangallo** [Azure/app-service-announcements-discussions#68]
While running **Node application** in Azure function apps:

- with runtime version **2.0.12050.0**  for following route path in function.json: 
           "route": "surveys/{surveyId?}/{relatedEntity?}" context.bindingData is not containing "surveyId" or "relatedEntity" (**_undefined_**)  when calling "surveys/" (without any surveyId and relatedEntity values). 

- with runtime version **2.0.12095.0** for following route path in function.json: 
           "route": "surveys/{surveyId?}/{relatedEntity?}" context.bindingData contains: surveyId: {} ,  relatedEntity: {} ( **_empty objects_** ) when calling surveys/ (without any surveyId and relatedEntity values)

**Comment by davidebbo** [comment]
So are you saying that 12050 was broken, and 12095 works? If that's not what you mean, please clarify what you view as the expected behavior.

**Comment by antoniopangallo** [comment]
Sorry If I was not clear. 

- with runtime version **2.0.12050.0**: context.bindingData of any optionals params if not passed, it was **undefined** as I would expect to be.

- with runtime version **2.0.12095.0**: context.bindingData of any optionals params if not passed, it is not undefined but an **empty object** as I would not expect to be.

Let's suppose I define a route like: "surveys/{surveyId?}/{relatedEntity?}".

**surveyId** and **relatedEntity** both are optionals and in the previous releases when I was looking for them in the context.bindingData object they were **undefined**, in the new release I am getting an **empty object** {}

What I am saying is this:  in my opinion the version **2.0.12050.0** was working as it should, because if a param is not passed it should not be a prop of the context.bindingData object but it should be **undefined** as it was before the new release.

Hope I clarified the issue I am getting. 

Thanks.

**Comment by davidebbo** [comment]
@antoniopangallo understood, thanks. We will investigate and get back to you.

**Comment by fabiocav** [comment]
This is indeed an issue with optional parameter handling that was introduced in that version (and more generally, an issue with how binding data flows into the language worker).

The good news is that when the optional parameter fix was added, the HTTP request handling was correctly updated, so you can get the exact behavior you're looking for by going to `context.req.params` instead of looking at binding data. We'll have this fixed so binding data behaves as it did.
