### ISSUE TITLE
[Discussion] Set your V1 Function Apps to ~1

### ISSUE THREAD

**Issue by paulbatum** [Azure/app-service-announcements-discussions#69]
Discussion issue for https://github.com/Azure/app-service-announcements/issues/135

**Comment by tomkerkhove** [comment]
Do I understand this correctly that all v1 customers will need to verify this before v2 is applied?

**Comment by jeffhollan** [comment]
The large majority of v1 apps **don't** have version set to something ambiguous like "" or "latest", but there are a subset that do. It's worth double checking and we've also been working to notify subscriptions directly to let them know they may be impacted

**Comment by tomkerkhove** [comment]
Thanks for the clarification & tip @jeffhollan :+1:

**Comment by Strandfelt** [comment]
@fabiocav @paulbatum This announcement is currently flagging our Azure Functions on the Flex Consumption plan. However, according to documentation, it is not required on this plan: https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#flex-consumption-plan-deprecations

![Image](https://github.com/user-attachments/assets/d720c5fe-6542-4ed1-bed3-2ec5ecf85a62)
