### ISSUE TITLE
[Discussion] Azure Functions Runtime 2.0.12115

### ISSUE THREAD

**Issue by paulbatum** [Azure/app-service-announcements-discussions#70]
Discussion issue for https://github.com/Azure/app-service-announcements/issues/136

**Comment by NickDarvey** [comment]
Is this release GA? Is Azure Functions ~2 now considered GA? (Not beta, preview, etc.)

**Comment by paulbatum** [comment]
Great question :) You'll hear from us loud and clear when functions V2 is GA.

**Comment by ferantivero** [comment]
I wanted to give a try on Azure to 2.0.12115 new runtime version and this is what I've got:

> Unsupported Runtime Version
> Your custom runtime version is not supported. As a result 2.0.12095.0 runtime is being used.

**Comment by davidebbo** [comment]
@ferantivero It is not yet deployed everywhere. Can you try in North Central US?

**Comment by ferantivero** [comment]
thanks @davidebbo northcentralus up & running 

<img width="194" alt="image" src="https://user-images.githubusercontent.com/158487/45841666-e120db80-bcf0-11e8-9cb7-2c3eee4688ea.png">

**Comment by pauldorehill** [comment]
It seems the known issues page has disappeared? 
https://github.com/Azure/azure-functions-host/wiki/Azure-Functions-runtime-2.0-known-issues

**Comment by pauldorehill** [comment]
@fabiocav thanks for the quick reply - I think one important thing is:

> Missing HttpRequestMessage extension methods from WebApi client packages (e.g. GetQueryNameValuePairs, CreateResponse). The assembly is not registered by default and the approach is to either reference the package or bind to HttpRequest instead.

With `Microsoft.NET.Sdk.Functions 1.0.22` this is still the case: all the online examples/documentation use `HttpRequestMessage`. 

I actually couldn't find a way to reference the correct assembly that has the ` HttpRequestMessage` extension methods and is supported by netstandard2.0?

**Comment by pauldorehill** [comment]
@TurtleBeach I think that would be useful and I had similar issue the other day. I am writing to Azure Tables which returns an `int` status code: it would be useful to be able to pass back into the `HttpResponseMessage`, but instead I have to do my own test:
```
let onTableAccess (tableResult : TableResult) =
    let result = string tableResult.HttpStatusCode
    if result.StartsWith "2" then Ok tableResult
    else
        let r = new HttpResponseMessage()
        r.StatusCode <- HttpStatusCode.BadRequest
        Error r
```

**Comment by paulbatum** [comment]
I can now confirm that this is the GA release - see https://github.com/Azure/app-service-announcements/issues/138

Since there is some discussion of Java in this thread I should note that Java support in Azure Functions is not yet GA and remains in preview.

**Comment by igorgnedish** [comment]
Hi all. It seems like with update to the most recent runtime version proxies have been broken again. 
It was previously fixed by https://github.com/Azure/azure-functions-host/issues/3466
but today I can see they do not work again (it affects autoscaling scenarios). So I downgraded runtime to 2.0.12050 and they started to work again. But I would like to have this bug fixed not to pin my app to the version which is going to be outdated soon :-) 

thanks

**Comment by davidebbo** [comment]
@igorgnedish this is tracked by https://github.com/Azure/azure-functions-host/issues/3533

**Comment by NickDarvey** [comment]
@odd-rune has anyone from Microsoft responded to you regarding this? (I saw you posted it in a few places.) We're seeing this issue too.

**Comment by davidebbo** [comment]
@odd-rune can you share your support case # so we can correlate with our internal investigation? Thanks!

**Comment by davidebbo** [comment]
Actually, @odd-rune, never mind. Talking to others, I see you are already the person which case they are investigating. @pragnagopa will open a new GitHub issue to better track this.

**Comment by davidebbo** [comment]
@odd-rune / @NickDarvey: let's use https://github.com/Azure/azure-functions-host/issues/3600 to discuss further.
