### ISSUE TITLE
[Discussion] Azure Functions 2.0 is generally available

### ISSUE THREAD

**Issue by paulbatum** [Azure/app-service-announcements-discussions#71]
Discussion issue for https://github.com/Azure/app-service-announcements/issues/138

**Comment by dalmat36** [comment]
Is support for Java in GA?

**Comment by davidebbo** [comment]
@dalmat36 The Java support is still in Preview.

**Comment by mamoorkhan** [comment]
is C# only supported in .NET Core and not on the .NET Framework in v2?

**Comment by paulbatum** [comment]
Azure Functions V2 only runs on .NET Core. There is no capability to run on .NET Framework.
