### ISSUE TITLE
[Discussion] Azure Functions Runtime 2.0.12134

### ISSUE THREAD

**Issue by fabiocav** [Azure/app-service-announcements-discussions#72]
Discussion for https://github.com/Azure/app-service-announcements/issues/141

**Comment by ggirard07** [comment]
This runtime version is relying on Webjobs [3.0.1](https://github.com/Azure/azure-webjobs-sdk/releases/tag/v3.0.1) based on [relase notes](https://github.com/Azure/azure-functions-host/releases/tag/v2.0.12134) but it seems to not be available on NuGet yet.
Can you publish it so everyone can benefit the fixes it contains?

**Comment by fabiocav** [comment]
@ggirard07 those will be published by the end of the week.

**Comment by Jeremywhiteley** [comment]
Is there a way to roll back to a prior runtime?  Otherwise I can’t do anything until next week.

**Comment by fabiocav** [comment]
@Jeremywhiteley there are no breaking changes or behavior differences with that update. This is fully backwards compatible and should not cause any issues with existing apps. 

You can roll back to the previous version by setting the `FUNCTIONS_EXTENSION_VERSION` to `2.0.12115`, but if you can share your function app name (or the information requested when you create an issue [here](https://github.com/Azure/azure-functions-host/issues), we can take a look at your app to investigate what is going on there. Again, a package update is not required and this a fully backwards compatible release, so we definitely want to  understand what is happening there.

**Comment by Jeremywhiteley** [comment]
@fabiocav In the process of putting together the code to share,  I found the error.  

If you go to this page, [https://github.com/Azure/azure-functions-host/wiki/host.json-(v2)#sample-hostjson](https://github.com/Azure/azure-functions-host/wiki/host.json-(v2)#sample-hostjson)

The CosmosDB code is missing a  ` : `  after `"cosmosDB"` and before the `{`
So it should be:  

   ` "cosmosDB": {
            "connectionMode": "Gateway",
            "protocol": "Https",
            "leaseOptions": {
                "leasePrefix": "prefix1"
            }
        }, `

Once I fixed this, It worked.  I can't believe I didn't catch it!  Can you please update the[ page](https://github.com/Azure/azure-functions-host/wiki/host.json-(v2)#sample-hostjson)?
Thank you for your help!

**Comment by fabiocav** [comment]
Glad to hear this is working, though!

**Comment by davidebbo** [comment]
The deployment is complete.
