### ISSUE TITLE
[Discussion] Azure Functions Runtime 1.0.12154 release

### ISSUE THREAD

**Issue by maiqbal11** [Azure/app-service-announcements-discussions#73]
Discussion issue for the Azure Functions runtime release 1.0.12154

**Comment by jfricioni** [comment]
Hi, just wanted to check to see if there is a force cut-over date setup for this function app version release?

**Comment by maiqbal11** [comment]
> Hi, just wanted to check to see if there is a force cut-over date setup for this function app version release?

There isn't a force cut-over date. We would recommend upgrading as the new release has fixes.

**Comment by maiqbal11** [comment]
Release is schedule to begin during the week of 5th November.

**Comment by maiqbal11** [comment]
Release is schedule to begin during the week of 5th November.

**Comment by maiqbal11** [comment]
The release has been completed
