### ISSUE TITLE
[Discussion] Azure Functions Runtime 2.0.12210

### ISSUE THREAD

**Issue by soninaren** [Azure/app-service-announcements-discussions#77]
Discussion issue for the Azure Functions Runtime release 2.0.12210

**Comment by brandonh-msft** [comment]
Hey @soninaren 
I am wondering; could we have issues 'Opened' when deployment starts, and 'Closed' when deployment is complete? Right now the Announcements Issues are just a bunch of open issues, no way to know when something has completed its deployment.

Thoughts?

**Comment by soninaren** [comment]
@brandonh-msft I think that is a reasonable thing to do.
@fabiocav , @jeffhollan  any thoughts on this?

**Comment by jnevins-gcm** [comment]
Does support for function instance methods also mean that constructor DI works for function method classes?

**Comment by fabiocav** [comment]
@jnevins-gcm it means constructor injection is supported. There are still some limitations (that's why it's not being positioned as the full DI solution tracked by this: https://github.com/Azure/azure-functions-host/issues/3736), but it's a step towards completing that item.
