### ISSUE TITLE
Issue when deploying ASP.NET Core 2.0 app to Azure Web App instance

### ISSUE THREAD

**Issue by sebastianbk** [Azure/app-service-announcements-discussions#8]
I just went and deployed my app targeting `netcoreapp2.0` using my release definition in VSTS and it seemed to deploy and start correctly. However, when navigating to [my site](https://staging.sensomind.com/) I got a 503 (Service Unavailable) error. Then after refreshing the page, I am now constantly getting this message:

```
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```

It seems as if it does hit the application but that it is caught in a loop of redirects (or something like it). The path shown in my browser atleast indicates this:

```
https://staging.sensomind.com/Account/LogIn?ReturnUrl=%2FHome%2FError%3FReturnUrl%3D%252FHome%252FError%253FReturnUrl%253D%25252FHome%25252FError%25253FReturnUrl%25253D%2525252FHome%2525252FError%2525253FReturnUrl%2525253D%252525252FHome%252525252FError%252525253FReturnUrl%252525253D%25252525252FHome%25252525252FError%25252525253FReturnUrl%25252525253D%2525252525252FHome%2525252525252FError%2525252525253FReturnUrl%2525252525253D%252525252525252FHome%252525252525252FError%252525252525253FReturnUrl%252525252525253D%25252525252525252FHome%25252525252525252FError%25252525252525253FReturnUrl%25252525252525253D%2525252525252525252FHome%2525252525252525252FError%2525252525252525253FReturnUrl%2525252525252525253D%252525252525252525252FHome%252525252525252525252FError%252525252525252525253FReturnUrl%252525252525252525253D%25252525252525252525252FHome%25252525252525252525252FError%25252525252525252525253FReturnUrl%25252525252525252525253D%2525252525252525252525252FHome%2525252525252525252525252FError%2525252525252525252525253FReturnUrl%2525252525252525252525253D%252525252525252525252525252FHome%252525252525252525252525252FError%252525252525252525252525253FReturnUrl%252525252525252525252525253D%25252525252525252525252525252FHome%25252525252525252525252525252FError%25252525252525252525252525253FReturnUrl%25252525252525252525252525253D%2525252525252525252525252525252FHome%2525252525252525252525252525252FError%2525252525252525252525252525253FReturnUrl%2525252525252525252525252525253D%252525252525252525252525252525252FHome%252525252525252525252525252525252FError%252525252525252525252525252525253FReturnUrl%252525252525252525252525252525253D%25252525252525252525252525252525252FHome%25252525252525252525252525252525252FError%25252525252525252525252525252525253FReturnUrl%25252525252525252525252525252525253D%2525252525252525252525252525252525252FHome%2525252525252525252525252525252525252FError%2525252525252525252525252525252525253FReturnUrl%2525252525252525252525252525252525253D%252525252525252525252525252525252525252FHome%252525252525252525252525252525252525252FError%252525252525252525252525252525252525253FReturnUrl%252525252525252525252525252525252525253D%25252525252525252525252525252525252525252F
```

I have tried cleaning the whole `wwwroot` directory, redeploying the app and restarting the Web App instance. However, none of it seems to work. I haven't had this issue before so I am unsure of how to resolve it.

If it is of any help, here is my `web.config`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="104857600" />
      </requestFiltering>
    </security>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\Sensomind.Web.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
<!--ProjectGuid: 618C309E-CB11-4876-BF8C-08B1E1DA7178-->
```

**Comment by sebastianbk** [comment]
I just tried creating a new Web App instance and deployed my app on it. I get exactly the same error again.

I am very confused about this error, as it works fine when debugging (using IIS Express) on my local dev machine. It does seem as if the app is being started correctly with the `dotnet Sensomind.Web.dll` command. This event (from `D:\home\LogFiles\eventlog.xml`, see below) also indicates that things have been deployed and started as they should. However, when navigating to the page I am being caught in this infinite redirect loop.

```xml
<Events>
    <Event>
        <System>
            <Provider Name="IIS AspNetCore Module"/>
            <EventID>1001</EventID>
            <Level>0</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2017-08-15T14:36:20Z"/>
            <EventRecordID>749672515</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD0003FF30EFCA</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Application 'MACHINE/WEBROOT/APPHOST/SENSOMIND__C0C3' started process '4368' successfully and is listening on port '7816'.</Data>
        </EventData>
    </Event>
</Events>
```

**Comment by davidebbo** [comment]
Not sure what's going on, but it could be some kind of app issue with the logic that chooses to redirect to the login page.

If you use Chrome F12 tools and check 'Preserve log', you can see the who redirect chain. Basically, it seems /Account/LogIn redirects to itself, each time adding the full current URL as the ReturnURL:

    https://staging.sensomind.com/
    https://staging.sensomind.com/Account/LogIn?ReturnUrl=%2F
    https://staging.sensomind.com/Account/LogIn?ReturnUrl=%2FHome%2FError%3FReturnUrl%3D%252F
    https://staging.sensomind.com/Account/LogIn?ReturnUrl=%2FHome%2FError%3FReturnUrl%3D%252FHome%252FError%253FReturnUrl%253D%25252F
    ...

Maybe that can give you some idea what might be going on?

Might be best to take to an ASP.NET Core forum as their experts may have more ideas.

**Comment by davidebbo** [comment]
Check out https://github.com/aspnet/IISIntegration/issues/140, which might be related.

**Comment by sebastianbk** [comment]
Thanks a lot, @davidebbo. I am gonna check it out and post a solution back here when I find one.

**Comment by sebastianbk** [comment]
Turns out to be an App Insights-related error that only occurs on Azure App Service. At least I couldn't reproduce it on my local machine with IIS Express nor on an IIS server I have sitting on my local network.

Created an issue for it here: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/515

I appreciate the support from you and your colleagues, @davidebbo. The new and open Microsoft is an awesome company!
