### ISSUE TITLE
[Discussion] In-portal editing will be disabled for Python Functions

### ISSUE THREAD

**Issue by jeffhollan** [Azure/app-service-announcements-discussions#88]
Discussion for the announcement to [remove portal editing for Python Functions](https://github.com/Azure/app-service-announcements/issues/157)

**Comment by mdgrotheer** [comment]
I might've missed the reason, but why was editing from the portal removed for Python Functions? Is it a preview issue? I understand that Python Functions can be deployed through the CLI, but just curious on the reason for this.

**Comment by asavaritayal** [comment]
@mdgrotheer in-portal editing for Python requires more investment to support streaming logs, installation of third-party packages, etc. so we decided to de-emphasize it for now. The plan is to bring a first-class experience back in the future. Exact timeline TBD.

**Comment by wwkeyboard** [comment]
This should be mentioned in the docs, e.g. https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function does not say what os/language combination will allow someone to continue with the tutorial.

**Comment by Cescante** [comment]
Also would be nice to mention in which locations a resource is available. Apparently python is only supported on Linux Function Apps, and Linux function apps are not available in CentralUS.

![image](https://user-images.githubusercontent.com/2474951/65266462-f8430680-dac7-11e9-85b3-9b05b6de8da0.png)

**Comment by Karlheinzniebuhr** [comment]
This should be explicitly documented on the Azure UI

**Comment by sheecegardezi** [comment]
Any updates on when python will be supported in other regions like Australia? and 
Is there a road map when support to edit python in web portal will be available ?

**Comment by anthonychu** [comment]
@shreyabatra4 @stefanushinardi can help answer
