### ISSUE TITLE
[Discussion] Azure Functions Python Runtime Bundler Breaking Change

### ISSUE THREAD

**Issue by maiqbal11** [Azure/app-service-announcements-discussions#91]
Discussion issue for https://github.com/Azure/app-service-announcements/issues/169.

**Comment by zak-jama-venture1consulting-com** [comment]
Can we republish it now or do we need to wait till the breaking change? 

Thanks.

**Comment by maiqbal11** [comment]
@zak-jama-venture1consulting-com, you can republish now. You will need azure-functions-core-tools version 2.5.553 or greater for this to work. We meant this as an advanced notice so we can get people moved over before we make the breaking change.
