### ISSUE TITLE
[Discussion] Azure Functions Runtime 2.0.12438

### ISSUE THREAD

**Issue by mhoeger** [Azure/app-service-announcements-discussions#93]
Discussion issue for the Azure Functions runtime release 2.0.12438

**Comment by ishepherd** [comment]
@mathewc re "Update WEBSITE_HOSTNAME environment variable correctly (#4162)"

To confirm, does this mean this env var will be correct now?

Or is it just that you have worked out an alternative to avoid using the buggy value?

**Comment by mathewc** [comment]
No, the environment variable will still be incorrect after swaps. We're working around that.

**Comment by ishepherd** [comment]
Ah, ok. Bummer.

**Comment by ishepherd** [comment]
(maybe fix the release note?)

**Comment by brettsam** [comment]
Deployment is complete.
